# Generated by Django 3.0.4 on 2020-03-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='score',
            name='github_link',
            field=models.CharField(default='https://github.com', max_length=255),
        ),
    ]
