# Generated by Django 3.0.4 on 2020-03-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_score_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='alias',
            field=models.CharField(default='', max_length=255),
        ),
    ]
