# Generated by Django 3.0.4 on 2020-03-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_auto_20200327_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='description',
        ),
        migrations.RemoveField(
            model_name='score',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='score',
            name='path_to_file',
        ),
        migrations.AlterField(
            model_name='score',
            name='slug',
            field=models.CharField(max_length=255),
        ),
    ]
