# Generated by Django 3.0.4 on 2020-04-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_score_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='is_finished',
        ),
    ]
