# Generated by Django 3.0.4 on 2020-05-18 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0012_auto_20200518_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='score',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='scores.Instrument'),
        ),
        migrations.AlterField(
            model_name='score',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
