# Generated by Django 3.0.4 on 2020-05-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0013_auto_20200518_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='datetime_created',
            field=models.DateTimeField(editable=False),
        ),
    ]
