# Generated by Django 3.1 on 2020-09-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0015_auto_20200519_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='datetime_created',
            new_name='timestamp',
        ),
    ]
