#!/bin/bash -e

if [ -z "$MYMUSICHERE_REMOTE" ]; then
    echo '$MYMUSICHERE_REMOTE is not set'
    exit 1
fi

if [ -z "$MYMUSICHERE_REPO_DIR" ]; then
    echo '$MYMUSICHERE_REPO_DIR is not set'
    exit 1
fi

if [ -z "$MYMUSICHERE_ARTIFACTS_DIR" ]; then
    echo '$MYMUSICHERE_ARTIFACTS_DIR is not set'
    exit 1
fi

if [ -d "$MYMUSICHERE_REPO_DIR" ]; then
    cd "$MYMUSICHERE_REPO_DIR"
    git pull
    make
    find $MYMUSICHERE_ARTIFACTS_DIR/* -type d -exec rm -r {} +
    mv out/* $MYMUSICHERE_ARTIFACTS_DIR/
else
    cd "$(dirname $MYMUSICHERE_REPO_DIR)"
    git clone "$MYMUSICHERE_REMOTE"
    cd "mymusichere"
    make
    find $MYMUSICHERE_ARTIFACTS_DIR/* -type d -exec rm -r {} +
    mv out/* $MYMUSICHERE_ARTIFACTS_DIR/
fi

