#!/bin/bash -e

if [ -z "$MYMUSICHERE_REMOTE" ]; then
    echo '$MYMUSICHERE_REMOTE is not set'
    exit 1
fi

if [ -d scores/lilypond ]; then
    cd scores/lilypond
    git pull
    make clean
    make
    cd ../..
    make static
else
    cd scores
    git clone "$MYMUSICHERE_REMOTE" lilypond
    cd lilypond
    make
    cd ../..
    make static
fi

