# Generated by Django 3.0.4 on 2020-03-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20200325_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='alias',
            field=models.TextField(default='', max_length=255),
        ),
    ]
